export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-[#FAFAFA] font-body text-dark">
      <div className="max-w-3xl mx-auto px-6 py-20">
        <a href="/" className="text-sm text-[#5BC0EB] hover:underline mb-8 inline-block">← Back to home</a>

        <h1 className="font-heading text-4xl font-semibold text-dark mb-2">Privacy Policy & Terms of Service</h1>
        <p className="text-sm text-dark/50 mb-10">Last updated: July 2026</p>

        {/* Privacy Nutrition Label */}
        <div className="mb-12 border-2 border-dark rounded-2xl overflow-hidden max-w-sm">
          <div className="bg-dark text-white px-5 py-4">
            <h2 className="font-heading text-2xl font-bold tracking-tight">Privacy Nutrition Label</h2>
            <p className="text-white/60 text-xs mt-1">A plain-English summary of how we handle your data</p>
          </div>
          {[
            { label: "Data sold to third parties", value: "Never", good: true },
            { label: "Data used for advertising", value: "Never", good: true },
            { label: "Data shared with AI provider (Groq)", value: "Session content only, to generate responses", good: null },
            { label: "AI training on your data", value: "No", good: true },
            { label: "Data encrypted at rest", value: "Yes (Supabase RLS)", good: true },
            { label: "You can delete your data", value: "Yes, anytime", good: true },
            { label: "Tracks you across other sites", value: "No", good: true },
            { label: "Requires real name", value: "No", good: true },
            { label: "Children under 13", value: "Not permitted", good: null },
          ].map(({ label, value, good }) => (
            <div key={label} className="flex items-start justify-between gap-4 px-5 py-3 border-t border-gray-200">
              <span className="text-sm text-dark/70">{label}</span>
              <span className={`text-sm font-semibold shrink-0 ${good === true ? "text-emerald-600" : good === false ? "text-red-500" : "text-amber-600"}`}>
                {value}
              </span>
            </div>
          ))}
        </div>

        {[
          {
            title: "1. Data We Collect",
            body: `When you use TutorGuide AI, we collect and store:\n• Session metadata (date, time, duration, subject, topic)\n• Student names and profiles (optional, entered by you)\n• AI coaching chat logs\n• Live session speech transcripts\n• Student emotional state indicators\n• Post-session reflection reports\n• Your name and email address (used for your account)`
          },
          {
            title: "2. How We Use Your Data",
            body: "Your data is used solely to display your past sessions and student progress within the app. We do not sell, share, or use your data for advertising or any third-party purpose."
          },
          {
            title: "3. Data Storage & Security",
            body: "All data is stored in Supabase with Row Level Security (RLS) enforced at the database level. This means your data is cryptographically isolated — no other user can access it, even if they are authenticated. Access controls are enforced server-side, not just in the app."
          },
          {
            title: "4. Authentication",
            body: "You may sign in using email/password or Google OAuth. When you use Google Sign-In, authentication is handled by Google and subject to Google's Privacy Policy (policies.google.com/privacy). We receive only your name and email address from Google — we do not receive your Google password or any other Google account data."
          },
          {
            title: "5. Use of Artificial Intelligence",
            body: `TutorGuide AI uses third-party AI services to generate coaching responses:\n• Coaching advice, hints, session plans, and reflection reports are generated by Groq's API using the Llama large language model.\n• Your session content (subject, topic, transcript excerpts, and chat messages) is sent to Groq's servers solely to generate your response. This data is not used to train AI models.\n• AI-generated responses may not always be accurate. You are responsible for verifying any advice before applying it in a session.\n• Do not enter sensitive personal information (e.g. student last names, school names, addresses) into the AI chat.`
          },
          {
            title: "6. Student Privacy",
            body: "You are responsible for obtaining appropriate consent from students and parents/guardians before entering student names or recording session transcripts. Do not enter personally identifiable information beyond what is necessary."
          },
          {
            title: "7. FERPA Notice",
            body: "If TutorGuide AI is used in a school or institutional setting, you (the tutor) are responsible for ensuring compliance with the Family Educational Rights and Privacy Act (FERPA) and any applicable state laws. TutorGuide AI is a tool for individual tutors and is not a FERPA-compliant service provider."
          },
          {
            title: "8. Data Retention & Deletion",
            body: "Your data is retained until you delete it. You may delete any session, student record, or your entire account at any time from within the app. Deleted data is permanently removed and cannot be recovered."
          },
          {
            title: "9. Dispute Resolution & Arbitration",
            body: `PLEASE READ THIS SECTION CAREFULLY — IT AFFECTS YOUR LEGAL RIGHTS.\n\nAny dispute, claim, or controversy arising out of or relating to these Terms or your use of TutorGuide AI shall be resolved by binding individual arbitration, not in court. You waive your right to a jury trial and your right to participate in a class action lawsuit or class-wide arbitration.\n\nArbitration shall be conducted under the rules of the American Arbitration Association (AAA). The arbitration will take place in the United States. Nothing in this clause prevents either party from seeking emergency injunctive relief in court to prevent irreparable harm.\n\nIf you do not agree to arbitration, you must notify us in writing at tutorguideai@gmail.com within 30 days of first using the service.`
          },
          {
            title: "10. Contact",
            body: "If you have questions or concerns about your data, contact us at tutorguideai@gmail.com."
          },
        ].map(({ title, body }) => (
          <div key={title} className="mb-8">
            <h2 className="font-heading text-lg font-semibold text-dark mb-2">{title}</h2>
            <p className="text-sm text-dark/70 leading-relaxed whitespace-pre-line">{body}</p>
          </div>
        ))}

        <div className="mt-10 pt-6 border-t border-gray-200">
          <p className="text-xs text-dark/40">By creating an account, you agree to these terms. © {new Date().getFullYear()} TutorGuide AI.</p>
        </div>
      </div>
    </div>
  );
}
